version: 1.0.{build}
build:
  verbosity: minimal
  
environment:
  matrix:
    - BUILD_TYPE: Release
      COMPILER: MSVC15
      PLATFORM: x64
    #- BUILD_TYPE: Release
    #  COMPILER: MSVC15
    #  PLATFORM: Win32
 
build_script:
  - if [%COMPILER%]==[MinGW-w64] mkdir bin && cd bin\ && appveyor DownloadFile http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe -fileName yasm.exe
  - if [%COMPILER%]==[MinGW-w64] C:\msys64\usr\bin\sh.exe --login /c/projects/mpir/.appveyor_msys_build.sh
  - if [%COMPILER%]==[MSVC15] cd build.vc14
  - if [%COMPILER%]==[MSVC15] msbuild.bat gc lib %PLATFORM% %BUILD_TYPE% # +tests

test_script:
  - if [%COMPILER%]==[MSVC15] cd mpir-tests

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - 7z a release.zip %APPVEYOR_BUILD_FOLDER%\lib\x64\Release\*
  - dir
  
artifacts:
  - path: release.zip
    name: LibRelease
